# Generated by Django 3.2.5 on 2021-10-21 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_following'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('follow_from', 'follow_to')},
        ),
    ]
