# Generated by Django 3.2.5 on 2021-10-21 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211021_2055'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='unique_followers',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('follow_from', 'follow_to')},
        ),
    ]
