version: "3"

services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    environment:
      - DB_HOST=db
      - DB_NAME=realtyna
      - DB_USER=root
      - DB_PASS=root

    command:
      sh -c "
      cd backend &&
      ./manage.py wait_for_db &&
      ./manage.py makemigrations &&
      ./manage.py migrate &&
      ./manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=realtyna
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

